name: Ro Halfhide
favicon: null
layout_spectrum: 0.10229441476985812
typography_spectrum: 0.15042941272258759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12134482618421316
  lightness: 0.7635617258492857
  saturation: 0.8363624839112163
  rhythmicContrast: 0.5913181151263416
purpose: []
